apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: gitlab
spec:
  applicationMenu:
    section: GitLab
    imageURL: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODAgMzgwIiB3aWR0aD0iNDgiIGhlaWdodD0iNDgiPgogIDxwYXRoIGZpbGw9IiNlMjQzMjkiIGQ9Ik0xOTAgMzUwLjhMMjUzLjIgMTU2LjRIMTI2Ljh6Ii8+CiAgPHBhdGggZmlsbD0iI2ZjNmQyNiIgZD0iTTE5MCAzNTAuOEwxMjYuOCAxNTYuNEgyNC40eiIvPgogIDxwYXRoIGZpbGw9IiNmY2EzMjYiIGQ9Ik0yNC40IDE1Ni40TDMuMiAyMjEuNmMtMS45IDUuOS4xIDEyLjMgNS4xIDE2TDE5MCAzNTAuOHoiLz4KICA8cGF0aCBmaWxsPSIjZTI0MzI5IiBkPSJNMjQuNCAxNTYuNEgxMjYuOEw4Mi44IDIwLjhjLTIuMi02LjgtMTEuOC02LjgtMTQgMHoiLz4KICA8cGF0aCBmaWxsPSIjZmM2ZDI2IiBkPSJNMTkwIDM1MC44TDI1My4yIDE1Ni40SDM1NS42eiIvPgogIDxwYXRoIGZpbGw9IiNmY2EzMjYiIGQ9Ik0zNTUuNiAxNTYuNEwzNzYuOCAyMjEuNmMxLjkgNS45LS4xIDEyLjMtNS4xIDE2TDE5MCAzNTAuOHoiLz4KICA8cGF0aCBmaWxsPSIjZTI0MzI5IiBkPSJNMzU1LjYgMTU2LjRIMjUzLjJMMjk3LjIgMjAuOGMyLjItNi44IDExLjgtNi44IDE0IDB6Ii8+Cjwvc3ZnPgo='
  href: "https://{{ .Values.gitlab.host }}"
  location: ApplicationMenu
  text: GitLab
