nameOverride: ""

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

tempoStack:
  namespace: tempo
  storageSize: 10Gi

minio:
  image: quay.io/minio/minio:latest
  rootUser: minio
  rootPassword: minio123
  bucket: tempo
  storageSize: 10Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd-immediate

tempo:
  host: ""
