nameOverride: ""

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

tempoStack:
  namespace: tempo
  storageSize: 10Gi
  obc:
    name: tempostack-dev-odf
    storageClassName: openshift-storage.noobaa.io
    endpoint: https://s3.openshift-storage.svc

tempo:
  host: ""
