apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-serving-ca
  namespace: {{ .Values.tempoStack.namespace }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    argocd.argoproj.io/sync-wave: "2"
