apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "openshift-tempo-og"
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-product
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  {{- if .Values.subscription.startingCSV }}
  startingCSV: {{ .Values.subscription.startingCSV }}
  {{- end }}
