apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
  namespace: {{ .Values.tempoStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  storage:
    secret:
      name: {{ .Values.tempoStack.obc.name }}-tempostack
      type: s3
    tls:
      caName: tempo-serving-ca
  storageSize: {{ .Values.tempoStack.storageSize }}
  template:
    queryFrontend:
      jaegerQuery:
        authentication:
          enabled: true
        enabled: true
