apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
  namespace: {{ .Values.tempoStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  storage:
    secret:
      name: tempostack-storage
      type: s3
  storageSize: {{ .Values.tempoStack.storageSize }}
  template:
    queryFrontend:
      jaegerQuery:
        authentication:
          enabled: true
        enabled: true
