apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo
  namespace: {{ .Values.tempoStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  storage:
    traces:
      backend: memory
  jaegerui:
    enabled: true
    route:
      enabled: true
