apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fullstack-dev-tools
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/workspace-images/parasol-insurance:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
