nameOverride: ""

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

kataconfig:
  checkNodeEligibility: false
  enablePeerPods: false
  logLevel: info
