{{- if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "backroom.metadata" (dict "name" .Values.observability.tempo.name "namespace" .Values.argocd.namespace "syncWave" "0") }}
spec:
  destination:
    namespace: {{ .Values.observability.tempo.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/tempo
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        subscription:
          source: {{ .Values.catalogSource.source }}
        tempo:
          host: tempo-tempo-query-frontend-{{ .Values.observability.tempo.namespace }}.{{ .Values.cluster.subdomain }}
{{ include "backroom.syncPolicy" . | indent 2 }}
{{- end }}
