nameOverride: ""

subscription:
  channel: stable
  installPlanApproval: Manual
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "opentelemetry-operator.v0.140.0-2"

collector:
  namespace: openshift-opentelemetry-operator
  mode: deployment
  exporters:
    otlp:
      enabled: false
      endpoint: "tempo-simplest-distributor.tempo:4317"
      insecure: true