apiVersion: batch/v1
kind: Job
metadata:
  name: otel-installplan-approve
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: otel-installplan-approver
      containers:
        - name: patch
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for OpenTelemetry InstallPlan to exist..."

              OPERATOR_NS="openshift-opentelemetry-operator"

              install_plan=""
              until [[ ${install_plan} != "" ]]
              do
                oc get installplan -n ${OPERATOR_NS}
                install_plan=$(oc get installplan -n ${OPERATOR_NS} | grep opentelemetry-operator | grep false | cut -d" " -f1)
                sleep 15
              done
              oc patch installplan ${install_plan} -n ${OPERATOR_NS} --type merge --patch '{"spec":{"approved":true }}'
              echo "OpenTelemetry InstallPlan Approved"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
